- name: Gather log files 
  hosts: myhosts 
  become: yes  
  
  tasks:    
    - name: List files to grab      
      find:       
        paths:          
         - /var/log        
        patterns:          
         - '*.log*'        
        recurse: yes    
      register: log_files    
    
    
