- name: Gather log files 
  hosts: servers  
  become: yes  
  
  tasks:    
    - name: List files to grab      
      find:       
        paths:          
         - /var/log        
        patterns:          
         - '*.log*'        
        recurse: yes    
      register: log_files    
    
    - name: Grab files      
      fetch:        
         src: "{{ item.path }}"        
         dest: "/tmp/LOGS_{{ Ansible_fqdn }}/"     
      with_items: "{{ log_files.files }}"
