---
- hosts: myhosts
  name: System Inventory
  gather_facts: False

  tasks:
  - name: Clone idrac from github
    git:
      repo: https://github.com/nirekr/idrac-ansible-module.git

  - name: Get the redfish module path
    command: python install.py

  - name: Define output file
    include_tasks: create_output_file.yml type=SystemInventory

  - name: Getting system inventory
    local_action: >
       redfish category=Inventory command=GetSystemInventory baseuri={{baseuri}}
       user={{user}} password={{password}}
    register: result

  - name: Copy results to output file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
