---
- hosts: myhosts
  name: System Inventory
  gather_facts: False

  tasks:
  - name: Clone idrac from github
    git:
      repo: https://github.com/nirekr/idrac-ansible-module.git
      dest: /opt/awx/idrac-ansible-module
      command: python /opt/awx/idrac-ansible-module/install.py

  - name: Get the redfish module path
    command: cd ../ && python /var/lib/awx/projects/_12__idrac_ansible_module/install.py

  - name: Define output file
    include_tasks: create_output_file.yml type=SystemInventory

  - name: Getting system inventory
    local_action: >
       pwd
       redfish category=Inventory command=GetSystemInventory baseuri={{baseuri}}
       user={{user}} password={{password}}
    register: result

  - name: Copy results to output file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
