---
- hosts: myhosts
  name: System Inventory
  gather_facts: False

  tasks:
  - name: Get the redfish module path
    command: python install.py
    args:
     chdir: /var/lib/awx/projects/_12__idrac_ansible_module/

  - name: Define output file
    include_tasks: create_output_file.yml type=SystemInventory

  - name: Getting system inventory
    local_action: >
       redfish category=Inventory command=GetSystemInventory baseuri={{baseuri}}
       user={{user}} password={{password}}
    register: result
  
  - set_fact:
      myvar:  "{{ result.stdout | from_json }}"

  - name: Copy results to output file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
